### ISSUE TITLE
报错 the Navigation prop is missing for this navigator

### ISSUE THREAD

**Issue by mike8625** [gaoxiaosong/react-native-full-image-picker#13]
需要的第三方库都装了最新版, 然后我一调用ImagePicker.getAlbum({}) 就报这个错误,实在不知道怎么解决了

**Comment by mike8625** [comment]
这样的:
Invariant Violation: The navigation prop is missing for this navigator. In 
react-navigation 3 you must set up your app container directly. More info: 
https://reactnavigation.org/docs/en/app-containers.html

**Comment by mike8625** [comment]
解决了,需要改源码PhotoModalPage.js的文件,加个container才能适应3.0版本

**Comment by shuiRong** [comment]
@mike8625 建议趁热把具体修改了哪些地方也贴出来，方便后来人
