### ISSUE TITLE
Error: Can't resolve './images/arrow_right.png'

### ISSUE THREAD

**Issue by namnm** [gaoxiaosong/react-native-full-image-picker#9]
In the src/images we have *3x.png files. Look like we need to rename them?

**Comment by namnm** [comment]
Also this error: Error: Can't resolve 'react-native/Libraries/Image/resolveAssetSource'
(using webpack)

**Comment by gaoxiaosong** [comment]
@namnm Sorry that I don't use webpack... `@3x` image is for React Native only, so why do not you use `node node_modules/react-native/local-cli/cli.js xxxxxxx` to start local debug server or bundle?

**Comment by namnm** [comment]
Because beside native app, we also build a web version of it via webpack and react-native-web. I think I should fork your repo meantime.

**Comment by gaoxiaosong** [comment]
@namnm You can fork and change file name without `@3x`, since `@3x` is for iOS and Android only. Or change code such as `Platform.OS === 'ios/android/web'` to `require` different image. Thanks for using it~~~

**Comment by gaoxiaosong** [comment]
@namnm If you think your code is general style, you can give me a pr~

**Comment by namnm** [comment]
Ok I think we will use other library to handle file picker in web by Platform.OS.
To fix webpack build error, we added `new webpack.IgnorePlugin(/react-native-full-image-picker/, /.*/)` to the plugins.
